### ISSUE TITLE
Inconsistent output from 32-bit vs 64-bit builds

### ISSUE THREAD

**Issue by Rupan** [AlexanderAmelkin/frugen#6] opened 2018-03-12 04:21 UTC
After writing the generated data out to a real FRU and running "ipmitool fru print" against it, I noticed that some data looked corrupted or was missing.  Long story short, it appears that frugen doesn't produce consistent output.  See, for example, [two files](https://github.com/AlexanderAmelkin/frugen/files/1801381/example-fru-data.zip) produced from "example.json".  The command line used was ```./frugen --from example.json x{86|64}.out```.  The only difference was that x86.out was produced using a 32-bit build while x64.out was produced using a 64-bit build.  I haven't dug into why this is happening, but there is a clear and reproducible difference in the outputs.

**Comment by AlexanderAmelkin** [comment] 2018-03-23 14:32
Thanks. I must check on this. However, please note that ipmitool is inherently buggy, especially in the fru part. Make sure you're using the latest version that includes at least [this](https://sourceforge.net/p/ipmitool/source/ci/497f7767cd8e80ad67d08680ae165271441017fc/) commit.

**Comment by AlexanderAmelkin** [comment] 2018-03-23 14:39
I've just checked your two files using `ipmitool -I dummy ekanalyzer frushow sm=<filename>` and can't see any difference except for the date and checksum. I used the latest ipmitool built from sources.

I checked them with `hexdump -vC` and can't find any difference (except for the same date part) in the files either.

So it looks like you're reporting an ipmitool bug, probably fixed with the commit I mentioned above.

If not fixed by that commit, then alas! The IPMItool project on sourceforge is currently orphaned for about a year now.

**Comment by Rupan** [comment] 2018-03-23 18:48
Indeed there may be some bug in ipmitool, but that was just reported as a symptom of the underlying problem.  The fact is that frugen produces two different outputs from the same input, depending on whether the binary is compiled in 32-bit or 64-bit mode.  This shouldn't be :)

**Comment by AlexanderAmelkin** [comment] 2018-03-26 14:02
The two files you have attached as an example of allegedly different outputs are **IDENTICAL** except for the date field and (hence) checksum. Either you have been mislead into thinking that the outputs are different by a bug in ipmitool, or you have attached wrong files. Please re-check on your side. If not confirmed, I'm going to close this issue.

**Comment by Rupan** [comment] 2018-03-26 15:23
I can completely ignore the ipmitool output here - I'm not using it.  I just built frugen from source in 32-bit and 64-bit mode and produced the output files attached using both versions.  ipmitool doesn't even enter the picture here since the FRU data has not been written to a BMC yet.

Since the input file is identical -- the example.json committed in the base of the repository -- the assumption is that the resulting binary FRU files should be identical.  The frugen code is not changed and the only difference is that one FRU file is produced with a 32-bit build and the other is produced with a 64-bit build.  Should the outputs not be identical, even down to the date field, in this case?

**Comment by Rupan** [comment] 2018-03-26 15:25
Are you using the current system time to generate the date field if it is not specified?  That would explain the discrepancy.  It isn't clear from the documentation as far as I can tell.

**Comment by AlexanderAmelkin** [comment] 2018-03-27 17:35
Yes, it is by design that when timestamp is not specified, the current system time is used. That makes using frugen on a factory easier.

You haven't read the documentation carefully enough. From README.md:

> For the most up-to-date information on the frugen tool invocation and options, please use frugen -h.

Then running `./frugen -h` gives you this:

```
$ ./frugen -h
FRU Generator v1.0.4.gdadc76a (c) 2016-2017, Alexander Amelkin <alexander@amelkin.msk.ru>
  
Usage: frugen [options] <filename>
  
Options:
        . . .  

        --board-date <argument>
                Set board manufacturing date/time, use "DD/MM/YYYY HH:MM:SS" format.
                By default the current system date/time is used.
```

It indeed may be unclear though that all the rules that apply to command line option arguments also apply to JSON fields and their values.

The date is given in `example.json` just for information on the field format, and is commented out by default exactly to achieve automated time-stamping.

**Closed by AlexanderAmelkin** 2018-03-27 17:35 UTC
